/**
 * THIS FILE IS AUTOGENERATED BY 'generateServiceClient.ts'.
 * DO NOT EDIT BY HAND.
 */

import { Request } from 'aws-sdk/lib/request'
import { Response } from 'aws-sdk/lib/response'
import { AWSError } from 'aws-sdk/lib/error'
import { Service } from 'aws-sdk/lib/service'
import { ServiceConfigurationOptions } from 'aws-sdk/lib/service'
import { ConfigBase as Config } from 'aws-sdk/lib/config-base'
interface Blob {}
declare class ClientMde extends Service {
    /**
     * Constructs a service object. This object has one method for each API operation.
     */
    constructor(options?: ClientMde.Types.ClientConfiguration)
    config: Config & ClientMde.Types.ClientConfiguration
    /**
     * Create a new, running environment from a definition and overrides asynchronously. Use the EventBridge for notification when the environment is &quot;RUNNING&quot; and therefore ready to StartSession, details.
     */
    createEnvironment(
        params: ClientMde.Types.CreateEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.CreateEnvironmentResponse) => void
    ): Request<ClientMde.Types.CreateEnvironmentResponse, AWSError>
    /**
     * Create a new, running environment from a definition and overrides asynchronously. Use the EventBridge for notification when the environment is &quot;RUNNING&quot; and therefore ready to StartSession, details.
     */
    createEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.CreateEnvironmentResponse) => void
    ): Request<ClientMde.Types.CreateEnvironmentResponse, AWSError>
    /**
     * Delete an environment from the system. Running environments and sessions will be stopped. If the environment does not exist a ResourceNotFoundException will be thrown (unless the clientToken matches a previous successful request).
     */
    deleteEnvironment(
        params: ClientMde.Types.DeleteEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.DeleteEnvironmentResponse) => void
    ): Request<ClientMde.Types.DeleteEnvironmentResponse, AWSError>
    /**
     * Delete an environment from the system. Running environments and sessions will be stopped. If the environment does not exist a ResourceNotFoundException will be thrown (unless the clientToken matches a previous successful request).
     */
    deleteEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.DeleteEnvironmentResponse) => void
    ): Request<ClientMde.Types.DeleteEnvironmentResponse, AWSError>
    /**
     * Retrieve Environment information for a given EnvironmentId
     */
    describeEnvironment(
        params: ClientMde.Types.DescribeEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.DescribeEnvironmentResponse) => void
    ): Request<ClientMde.Types.DescribeEnvironmentResponse, AWSError>
    /**
     * Retrieve Environment information for a given EnvironmentId
     */
    describeEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.DescribeEnvironmentResponse) => void
    ): Request<ClientMde.Types.DescribeEnvironmentResponse, AWSError>
    /**
     * Retrieve Session information for a given EnvironmentId and SessionId
     */
    describeSession(
        params: ClientMde.Types.DescribeSessionRequest,
        callback?: (err: AWSError, data: ClientMde.Types.DescribeSessionResponse) => void
    ): Request<ClientMde.Types.DescribeSessionResponse, AWSError>
    /**
     * Retrieve Session information for a given EnvironmentId and SessionId
     */
    describeSession(
        callback?: (err: AWSError, data: ClientMde.Types.DescribeSessionResponse) => void
    ): Request<ClientMde.Types.DescribeSessionResponse, AWSError>
    /**
     * Return the environments for a given account
     */
    listEnvironments(
        params: ClientMde.Types.ListEnvironmentsRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ListEnvironmentsResponse) => void
    ): Request<ClientMde.Types.ListEnvironmentsResponse, AWSError>
    /**
     * Return the environments for a given account
     */
    listEnvironments(
        callback?: (err: AWSError, data: ClientMde.Types.ListEnvironmentsResponse) => void
    ): Request<ClientMde.Types.ListEnvironmentsResponse, AWSError>
    /**
     * Return the Sessions for a given Environment
     */
    listSessions(
        params: ClientMde.Types.ListSessionsRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ListSessionsResponse) => void
    ): Request<ClientMde.Types.ListSessionsResponse, AWSError>
    /**
     * Return the Sessions for a given Environment
     */
    listSessions(
        callback?: (err: AWSError, data: ClientMde.Types.ListSessionsResponse) => void
    ): Request<ClientMde.Types.ListSessionsResponse, AWSError>
    /**
     *
     */
    listTagsForResource(
        params: ClientMde.Types.ListTagsForResourceRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ListTagsForResourceResponse) => void
    ): Request<ClientMde.Types.ListTagsForResourceResponse, AWSError>
    /**
     *
     */
    listTagsForResource(
        callback?: (err: AWSError, data: ClientMde.Types.ListTagsForResourceResponse) => void
    ): Request<ClientMde.Types.ListTagsForResourceResponse, AWSError>
    /**
     * Puts client's credentials on the environment. The credentials is an union of possible credentials (e.g. AWS, Github, etc). These credentials are pushed down to the environment and the identity of the client is verified. The credentials expected to be short living. The client is responsible for the updating the credentials. If the client does not have permissions to interact with the environment a AccessDeniedException will be thrown. If the customer identity does not match the IAM principal provided during the creation of the environment an AccessDeniedException will be thrown. If the environment does not exist a ResourceNotFoundException will be thrown. If we are unable to connect to the environment a ConflictException will be thrown.
     */
    putCredentials(
        params: ClientMde.Types.PutCredentialsRequest,
        callback?: (err: AWSError, data: ClientMde.Types.PutCredentialsResponse) => void
    ): Request<ClientMde.Types.PutCredentialsResponse, AWSError>
    /**
     * Puts client's credentials on the environment. The credentials is an union of possible credentials (e.g. AWS, Github, etc). These credentials are pushed down to the environment and the identity of the client is verified. The credentials expected to be short living. The client is responsible for the updating the credentials. If the client does not have permissions to interact with the environment a AccessDeniedException will be thrown. If the customer identity does not match the IAM principal provided during the creation of the environment an AccessDeniedException will be thrown. If the environment does not exist a ResourceNotFoundException will be thrown. If we are unable to connect to the environment a ConflictException will be thrown.
     */
    putCredentials(
        callback?: (err: AWSError, data: ClientMde.Types.PutCredentialsResponse) => void
    ): Request<ClientMde.Types.PutCredentialsResponse, AWSError>
    /**
     * Resume an existing session that has been transiently disconnected. For use by clients to automatically reconnect during intermittent network issues. It is not intended for any other use. If the session is not available or environment is not running a ConflictException will be thrown. If the session does not exist a ResourceNotFoundException will be thrown.
     */
    resumeSession(
        params: ClientMde.Types.ResumeSessionRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ResumeSessionResponse) => void
    ): Request<ClientMde.Types.ResumeSessionResponse, AWSError>
    /**
     * Resume an existing session that has been transiently disconnected. For use by clients to automatically reconnect during intermittent network issues. It is not intended for any other use. If the session is not available or environment is not running a ConflictException will be thrown. If the session does not exist a ResourceNotFoundException will be thrown.
     */
    resumeSession(
        callback?: (err: AWSError, data: ClientMde.Types.ResumeSessionResponse) => void
    ): Request<ClientMde.Types.ResumeSessionResponse, AWSError>
    /**
     * Start a previously stopped environment
     */
    startEnvironment(
        params: ClientMde.Types.StartEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StartEnvironmentResponse) => void
    ): Request<ClientMde.Types.StartEnvironmentResponse, AWSError>
    /**
     * Start a previously stopped environment
     */
    startEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.StartEnvironmentResponse) => void
    ): Request<ClientMde.Types.StartEnvironmentResponse, AWSError>
    /**
     * Start a session connected to a running environment, either SSM or SSH (via SSM). Multiple sessions can be connected to an environment at the same time. If the environment is not running a ValidationException is thrown. If we are unable to connect to the environment a ConflictException is thrown.
     */
    startSession(
        params: ClientMde.Types.StartSessionRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StartSessionResponse) => void
    ): Request<ClientMde.Types.StartSessionResponse, AWSError>
    /**
     * Start a session connected to a running environment, either SSM or SSH (via SSM). Multiple sessions can be connected to an environment at the same time. If the environment is not running a ValidationException is thrown. If we are unable to connect to the environment a ConflictException is thrown.
     */
    startSession(
        callback?: (err: AWSError, data: ClientMde.Types.StartSessionResponse) => void
    ): Request<ClientMde.Types.StartSessionResponse, AWSError>
    /**
     *
     */
    stopEnvironment(
        params: ClientMde.Types.StopEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StopEnvironmentResponse) => void
    ): Request<ClientMde.Types.StopEnvironmentResponse, AWSError>
    /**
     *
     */
    stopEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.StopEnvironmentResponse) => void
    ): Request<ClientMde.Types.StopEnvironmentResponse, AWSError>
    /**
     * Stop an existing session. Stopped sessions cannot be refreshed or restarted. If the environment does not exist a ResourceNotFoundException will be thrown. If session is not found a ValidationException will be thrown. (REVIEW) If we are unable to contact to the environment a ConflictException will be thrown.
     */
    stopSession(
        params: ClientMde.Types.StopSessionRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StopSessionResponse) => void
    ): Request<ClientMde.Types.StopSessionResponse, AWSError>
    /**
     * Stop an existing session. Stopped sessions cannot be refreshed or restarted. If the environment does not exist a ResourceNotFoundException will be thrown. If session is not found a ValidationException will be thrown. (REVIEW) If we are unable to contact to the environment a ConflictException will be thrown.
     */
    stopSession(
        callback?: (err: AWSError, data: ClientMde.Types.StopSessionResponse) => void
    ): Request<ClientMde.Types.StopSessionResponse, AWSError>
    /**
     *
     */
    tagResource(
        params: ClientMde.Types.TagResourceRequest,
        callback?: (err: AWSError, data: ClientMde.Types.TagResourceResponse) => void
    ): Request<ClientMde.Types.TagResourceResponse, AWSError>
    /**
     *
     */
    tagResource(
        callback?: (err: AWSError, data: ClientMde.Types.TagResourceResponse) => void
    ): Request<ClientMde.Types.TagResourceResponse, AWSError>
    /**
     *
     */
    untagResource(
        params: ClientMde.Types.UntagResourceRequest,
        callback?: (err: AWSError, data: ClientMde.Types.UntagResourceResponse) => void
    ): Request<ClientMde.Types.UntagResourceResponse, AWSError>
    /**
     *
     */
    untagResource(
        callback?: (err: AWSError, data: ClientMde.Types.UntagResourceResponse) => void
    ): Request<ClientMde.Types.UntagResourceResponse, AWSError>
}
declare namespace ClientMde {
    export interface AccessDetails {
        /**
         * A websocket url to connect to the environment
         */
        streamUrl?: StreamUrl
        /**
         * An opaque token used to authenticate requests
         */
        tokenValue?: TokenValue
    }
    export type AccessKeyId = string
    export type Arn = string
    export interface AwsCredentials {
        /**
         * The access key ID that identifies the temporary security credentials.
         */
        accessKeyId: AccessKeyId
        /**
         * The date on which the current credentials expire.
         */
        expiration: Timestamp
        /**
         * The last updated timestamp.
         */
        lastUpdated?: Timestamp
        /**
         * The secret access key that can be used to sign requests.
         */
        secretAccessKey: String
        /**
         * The token that users must pass to the service API to use the temporary credentials.
         */
        sessionToken: String
        /**
         * The type of AWS credentials, i.e. 'AWS-HMAC'
         */
        type?: String
    }
    export type ClientToken = string
    export type Command = CommandMemberString[]
    export type CommandMemberString = string
    export interface CreateEnvironmentRequest {
        clientToken?: ClientToken
        /**
         * The definition parameter provides the image, repo or compose file that defines the container setup for the new environment. If no definition is provided then a default environment is used.
         */
        definition?: Definition
        /**
         * The optional IDE runtime to use
         */
        ideRuntimes?: IdeRuntimesInput
        /**
         * The optional Instance Type to use for the MDE environment CPU and RAM
         */
        instanceType?: InstanceType
        /**
         * The optional KMS Key ARN used for encryption
         */
        kmsKeyID?: KmsKeyArn
        /**
         * The optional token that uniquely identifies a customer account for billing purposes
         */
        payerToken?: PayerToken
        /**
         * The optional Secret ARN to use for authentication when cloning a private repository
         */
        secretArn?: SecretArn
        /**
         * Tags to apply to the environment during creation
         */
        tags?: TagMap
        /**
         * The end user ID (customer using Cloud Shell, etc.)
         */
        userId: UserId
    }
    export interface CreateEnvironmentResponse {
        environment: Environment
    }
    export type CredentialsName = string
    export interface Definition {
        shellImage?: DefinitionShellImageString
        sourceCodeUris?: SourceCodeUris
    }
    export type DefinitionShellImageString = string
    export interface DeleteEnvironmentRequest {
        clientToken?: ClientToken
        environmentId: EnvironmentId
    }
    export interface DeleteEnvironmentResponse {
        /**
         * The Environment that was deleted
         */
        environment: Environment
    }
    export interface DescribeEnvironmentRequest {
        environmentId: EnvironmentId
    }
    export interface DescribeEnvironmentResponse {
        environment: Environment
    }
    export interface DescribeSessionRequest {
        environmentId: EnvironmentId
        sessionId: SessionId
    }
    export interface DescribeSessionResponse {
        session: Session
    }
    export interface Environment {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Creation timestamp in UTC
         */
        createTime?: Timestamp
        /**
         * Upper limit of Environment lifetime as a timestamp in UTC. Environments have a maximum duration of X hours and will be stopped and deleted after this time.
         */
        deadlineTime?: Timestamp
        /**
         * Definition used for this environment
         */
        definition?: Definition
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        environmentId: EnvironmentId
        /**
         * Optional IDE runtime to use
         */
        ideRuntimes?: IdeRuntimes
        /**
         * The optional Instance Type to use for the MDE environment CPU and RAM
         */
        instanceType?: InstanceType
        /**
         * Time of the last session activity, including start, refresh and resume as a timestamp in UTC. Environments with no activity for X minutes may be stopped and deleted.
         */
        lastSessionActivityTime?: Timestamp
        /**
         * Actual status of the environment, such as RUNNING
         */
        status?: EnvironmentStatus
        /**
         * Reason for the most recent stop of the environment
         */
        stoppedReason?: String
        /**
         * Tags of the environment
         */
        tags?: TagMap
        /**
         * The end customer ID
         */
        userId?: UserId
    }
    export type EnvironmentId = string
    export type EnvironmentStatus =
        | 'PENDING'
        | 'RUNNING'
        | 'STARTING'
        | 'STOPPING'
        | 'STOPPED'
        | 'DELETING'
        | 'DELETED'
        | string
    export type Environments = Environment[]
    export interface IdeRuntime {
        /**
         * The identifier of the IDE runtime
         */
        id: IdeRuntimeIdString
        /**
         * The version of the IDE runtime
         */
        version: IdeRuntimeVersionString
    }
    export type IdeRuntimeIdString = string
    export interface IdeRuntimeInput {
        /**
         * The identifier of the IDE runtime
         */
        id: IdeRuntimeInputIdString
    }
    export type IdeRuntimeInputIdString = string
    export type IdeRuntimeVersionString = string
    export type IdeRuntimes = IdeRuntime[]
    export type IdeRuntimesInput = IdeRuntimeInput[]
    export type InstanceType = 'mde.small' | 'mde.medium' | 'mde.large' | string
    export type KmsKeyArn = string
    export interface ListEnvironmentsRequest {
        limit?: MaxSize1000
        nextToken?: NextToken
    }
    export interface ListEnvironmentsResponse {
        environments?: Environments
        nextToken?: NextToken
    }
    export interface ListSessionsRequest {
        environmentId: EnvironmentId
        limit?: MaxSize200
        nextToken?: NextToken
    }
    export interface ListSessionsResponse {
        nextToken?: NextToken
        sessions?: Sessions
    }
    export interface ListTagsForResourceRequest {
        resourceArn: String
    }
    export interface ListTagsForResourceResponse {
        tags?: TagMap
    }
    export type MaxSize1000 = number
    export type MaxSize200 = number
    export type NextToken = string
    export type PayerToken = string
    export interface PutCredentialsRequest {
        credentials: SyntheticPutCredentialsRequestCredentials
        environmentId: EnvironmentId
        name: CredentialsName
    }
    export interface PutCredentialsResponse {
        /**
         * The environment that got credentials
         */
        environmentId: EnvironmentId
    }
    export interface ResumeSessionRequest {
        environmentId: EnvironmentId
        sessionId: SessionId
    }
    export interface ResumeSessionResponse {
        /**
         * Access details for the session, potentially new ones
         */
        accessDetails?: AccessDetails
        environmentId: EnvironmentId
        /**
         * The Session successfully refreshed
         */
        session?: Session
        sessionId: SessionId
    }
    export type SecretArn = string
    export interface Session {
        /**
         * Session end timestamp in UTC, if the session has ended
         */
        endTime?: Timestamp
        environmentId: EnvironmentId
        /**
         * Time of the last session refresh as a timestamp in UTC
         */
        lastActivityTime?: Timestamp
        sessionId: SessionId
        sessionStatus?: SessionStatus
        sessionType?: SessionType
        /**
         * Session creation timestamp in UTC
         */
        startTime?: Timestamp
    }
    export type SessionId = string
    export type SessionParameterName = string
    export type SessionParameterValue = string
    export type SessionParameterlist = SessionParameterValue[]
    export type SessionParameters = { [key: string]: SessionParameterlist }
    export type SessionStatus = 'CONNECTED' | 'DISCONNECTED' | string
    export type SessionType = 'SSM' | 'SSH' | string
    export type Sessions = Session[]
    export type SourceCodeUris = SourceCodeUrisMemberString[]
    export type SourceCodeUrisMemberString = string
    export interface StartEnvironmentRequest {
        clientToken?: ClientToken
        /**
         * New environment definition for the environment
         */
        definition?: Definition
        environmentId: EnvironmentId
        /**
         * New runtime to be used in the environment
         */
        ideRuntimes?: IdeRuntimesInput
        /**
         * The optional Instance Type to use for the MDE environment CPU and RAM
         */
        instanceType?: InstanceType
        /**
         * New Secret ARN to use for authentication when cloning a private repository
         */
        secretArn?: SecretArn
    }
    export interface StartEnvironmentResponse {
        environment: Environment
    }
    export interface StartSessionRequest {
        /**
         * Command for SSM to execute. The first list item is the command and the others are the arguments. If no command is provided then the default shell is launched. A maximum of 10 arguments can be provided. Note: this is only applicable to SSM sessions
         */
        command?: Command
        environmentId: EnvironmentId
        /**
         * Reserved for future use
         */
        parameters?: SessionParameters
        sessionType: SessionType
    }
    export interface StartSessionResponse {
        accessDetails?: AccessDetails
        environmentId: EnvironmentId
        sessionId: String
        sessionType?: SessionType
    }
    export interface StopEnvironmentRequest {
        clientToken?: ClientToken
        environmentId: EnvironmentId
    }
    export interface StopEnvironmentResponse {
        environment: Environment
    }
    export interface StopSessionRequest {
        clientToken?: ClientToken
        environmentId: EnvironmentId
        sessionId: SessionId
    }
    export interface StopSessionResponse {
        /**
         * The session that was stopped
         */
        session: Session
    }
    export type StreamUrl = string
    export type String = string
    export interface SyntheticPutCredentialsRequestCredentials {
        aws?: AwsCredentials
    }
    export type TagKeys = String[]
    export type TagMap = { [key: string]: TagMapValueString }
    export type TagMapKeyString = string
    export type TagMapValueString = string
    export interface TagResourceRequest {
        resourceArn: String
        tags: TagMap
    }
    export interface TagResourceResponse {}
    export type Timestamp = Date
    export type TokenValue = string
    export interface UntagResourceRequest {
        resourceArn: String
        tagKeys: TagKeys
    }
    export interface UntagResourceResponse {}
    export type UserId = string
    /**
     * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
     */
    export type apiVersion = '2020-04-05' | 'latest' | string
    export interface ClientApiVersions {
        /**
         * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
         */
        apiVersion?: apiVersion
    }
    export type ClientConfiguration = ServiceConfigurationOptions & ClientApiVersions
    /**
     * Contains interfaces for use with the ClientMde client.
     */
    export import Types = ClientMde
}
export = ClientMde
