/**
 * THIS FILE IS AUTOGENERATED BY 'generateServiceClient.ts'.
 * DO NOT EDIT BY HAND.
 */

import { Request } from 'aws-sdk/lib/request'
import { Response } from 'aws-sdk/lib/response'
import { AWSError } from 'aws-sdk/lib/error'
import { Service } from 'aws-sdk/lib/service'
import { ServiceConfigurationOptions } from 'aws-sdk/lib/service'
import { ConfigBase as Config } from 'aws-sdk/lib/config-base'
interface Blob {}
declare class ClientMde extends Service {
    /**
     * Constructs a service object. This object has one method for each API operation.
     */
    constructor(options?: ClientMde.Types.ClientConfiguration)
    config: Config & ClientMde.Types.ClientConfiguration
    /**
     * Create a new, running or stopped environment asynchronously. Use the EventBridge for notification when the environment is &quot;RUNNING&quot; and therefore ready to StartSession, details.
     */
    createEnvironment(
        params: ClientMde.Types.CreateEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.CreateEnvironmentResponse) => void
    ): Request<ClientMde.Types.CreateEnvironmentResponse, AWSError>
    /**
     * Create a new, running or stopped environment asynchronously. Use the EventBridge for notification when the environment is &quot;RUNNING&quot; and therefore ready to StartSession, details.
     */
    createEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.CreateEnvironmentResponse) => void
    ): Request<ClientMde.Types.CreateEnvironmentResponse, AWSError>
    /**
     * Delete an environment from the system. Running environments and sessions will be stopped. If the environment does not exist a ResourceNotFoundException will be thrown (unless the clientToken matches a previous successful request).
     */
    deleteEnvironment(
        params: ClientMde.Types.DeleteEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.DeleteEnvironmentResponse) => void
    ): Request<ClientMde.Types.DeleteEnvironmentResponse, AWSError>
    /**
     * Delete an environment from the system. Running environments and sessions will be stopped. If the environment does not exist a ResourceNotFoundException will be thrown (unless the clientToken matches a previous successful request).
     */
    deleteEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.DeleteEnvironmentResponse) => void
    ): Request<ClientMde.Types.DeleteEnvironmentResponse, AWSError>
    /**
     * Retrieve Environment information for a given EnvironmentId
     */
    getEnvironmentMetadata(
        params: ClientMde.Types.GetEnvironmentMetadataRequest,
        callback?: (err: AWSError, data: ClientMde.Types.GetEnvironmentMetadataResponse) => void
    ): Request<ClientMde.Types.GetEnvironmentMetadataResponse, AWSError>
    /**
     * Retrieve Environment information for a given EnvironmentId
     */
    getEnvironmentMetadata(
        callback?: (err: AWSError, data: ClientMde.Types.GetEnvironmentMetadataResponse) => void
    ): Request<ClientMde.Types.GetEnvironmentMetadataResponse, AWSError>
    /**
     * Retrieve Session information for a given EnvironmentId and SessionId
     */
    getSessionMetadata(
        params: ClientMde.Types.GetSessionMetadataRequest,
        callback?: (err: AWSError, data: ClientMde.Types.GetSessionMetadataResponse) => void
    ): Request<ClientMde.Types.GetSessionMetadataResponse, AWSError>
    /**
     * Retrieve Session information for a given EnvironmentId and SessionId
     */
    getSessionMetadata(
        callback?: (err: AWSError, data: ClientMde.Types.GetSessionMetadataResponse) => void
    ): Request<ClientMde.Types.GetSessionMetadataResponse, AWSError>
    /**
     * Return the environments for a given account
     */
    listEnvironments(
        params: ClientMde.Types.ListEnvironmentsRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ListEnvironmentsResponse) => void
    ): Request<ClientMde.Types.ListEnvironmentsResponse, AWSError>
    /**
     * Return the environments for a given account
     */
    listEnvironments(
        callback?: (err: AWSError, data: ClientMde.Types.ListEnvironmentsResponse) => void
    ): Request<ClientMde.Types.ListEnvironmentsResponse, AWSError>
    /**
     * Return the Sessions for a given Environment
     */
    listSessions(
        params: ClientMde.Types.ListSessionsRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ListSessionsResponse) => void
    ): Request<ClientMde.Types.ListSessionsResponse, AWSError>
    /**
     * Return the Sessions for a given Environment
     */
    listSessions(
        callback?: (err: AWSError, data: ClientMde.Types.ListSessionsResponse) => void
    ): Request<ClientMde.Types.ListSessionsResponse, AWSError>
    /**
     * List tags for resource
     */
    listTagsForResource(
        params: ClientMde.Types.ListTagsForResourceRequest,
        callback?: (err: AWSError, data: ClientMde.Types.ListTagsForResourceResponse) => void
    ): Request<ClientMde.Types.ListTagsForResourceResponse, AWSError>
    /**
     * List tags for resource
     */
    listTagsForResource(
        callback?: (err: AWSError, data: ClientMde.Types.ListTagsForResourceResponse) => void
    ): Request<ClientMde.Types.ListTagsForResourceResponse, AWSError>
    /**
     * Start a previously stopped environment
     */
    startEnvironment(
        params: ClientMde.Types.StartEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StartEnvironmentResponse) => void
    ): Request<ClientMde.Types.StartEnvironmentResponse, AWSError>
    /**
     * Start a previously stopped environment
     */
    startEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.StartEnvironmentResponse) => void
    ): Request<ClientMde.Types.StartEnvironmentResponse, AWSError>
    /**
     * Start a session connected to a running environment, either SSM or SSH (via SSM). Multiple sessions can be connected to an environment at the same time. If the environment is not running a ValidationException is thrown. If we are unable to connect to the environment a ConflictException is thrown.
     */
    startSession(
        params: ClientMde.Types.StartSessionRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StartSessionResponse) => void
    ): Request<ClientMde.Types.StartSessionResponse, AWSError>
    /**
     * Start a session connected to a running environment, either SSM or SSH (via SSM). Multiple sessions can be connected to an environment at the same time. If the environment is not running a ValidationException is thrown. If we are unable to connect to the environment a ConflictException is thrown.
     */
    startSession(
        callback?: (err: AWSError, data: ClientMde.Types.StartSessionResponse) => void
    ): Request<ClientMde.Types.StartSessionResponse, AWSError>
    /**
     * Stop environment operation stops a running environment
     */
    stopEnvironment(
        params: ClientMde.Types.StopEnvironmentRequest,
        callback?: (err: AWSError, data: ClientMde.Types.StopEnvironmentResponse) => void
    ): Request<ClientMde.Types.StopEnvironmentResponse, AWSError>
    /**
     * Stop environment operation stops a running environment
     */
    stopEnvironment(
        callback?: (err: AWSError, data: ClientMde.Types.StopEnvironmentResponse) => void
    ): Request<ClientMde.Types.StopEnvironmentResponse, AWSError>
    /**
     * Stop an existing session. Stopped sessions cannot be refreshed or restarted. If the environment does not exist a ResourceNotFoundException will be thrown. If session is not found a ValidationException will be thrown. (REVIEW) If we are unable to contact to the environment a ConflictException will be thrown.
     */
    stopSession(
        params: ClientMde.Types.StopSessionRequest,
        callback?: (err: AWSError, data: {}) => void
    ): Request<{}, AWSError>
    /**
     * Stop an existing session. Stopped sessions cannot be refreshed or restarted. If the environment does not exist a ResourceNotFoundException will be thrown. If session is not found a ValidationException will be thrown. (REVIEW) If we are unable to contact to the environment a ConflictException will be thrown.
     */
    stopSession(callback?: (err: AWSError, data: {}) => void): Request<{}, AWSError>
    /**
     * Tag resource operation
     */
    tagResource(
        params: ClientMde.Types.TagResourceRequest,
        callback?: (err: AWSError, data: ClientMde.Types.TagResourceResponse) => void
    ): Request<ClientMde.Types.TagResourceResponse, AWSError>
    /**
     * Tag resource operation
     */
    tagResource(
        callback?: (err: AWSError, data: ClientMde.Types.TagResourceResponse) => void
    ): Request<ClientMde.Types.TagResourceResponse, AWSError>
    /**
     * Untag resource operation
     */
    untagResource(
        params: ClientMde.Types.UntagResourceRequest,
        callback?: (err: AWSError, data: ClientMde.Types.UntagResourceResponse) => void
    ): Request<ClientMde.Types.UntagResourceResponse, AWSError>
    /**
     * Untag resource operation
     */
    untagResource(
        callback?: (err: AWSError, data: ClientMde.Types.UntagResourceResponse) => void
    ): Request<ClientMde.Types.UntagResourceResponse, AWSError>
}
declare namespace ClientMde {
    export interface AccessDetails {
        /**
         * A websocket url to connect to the environment
         */
        streamUrl?: StreamUrl
        /**
         * An opaque token used to authenticate requests
         */
        tokenValue?: TokenValue
    }
    export type Arn = string
    export type Boolean = boolean
    export type ClientToken = string
    export type Command = CommandMemberString[]
    export type CommandMemberString = string
    export interface CreateEnvironmentRequest {
        clientToken?: ClientToken
        /**
         * The definition parameter provides the image, repo or compose file that defines the container setup for the new environment. If no definition is provided then a default environment is used.
         */
        definition?: Definition
        /**
         * The optional Devfile to use
         */
        devfile?: DevfileConfiguration
        /**
         * The optional ARN of the execution role to be used for launching the environment
         */
        executionRoleArn?: IamRoleArn
        /**
         * The optional IDE runtimes to use
         */
        ideRuntimes?: IdeRuntimesConfiguration
        inactivityTimeoutMinutes?: InactivityTimeoutMinutes
        /**
         * The instance type to use for the MDE environment CPU and RAM
         */
        instanceType: InstanceType
        /**
         * Persistent storage configuration
         */
        persistentStorage: PersistentStorageConfiguration
        /**
         * The optional ARN of the role to be used within the environment
         */
        roleArn?: IamRoleArn
        /**
         * List of source code to clone after environment creation
         */
        sourceCode?: SourceCodeConfigurationList
        /**
         * Should the environment be started after successful creation (default: true)?
         */
        start?: Boolean
        /**
         * Tags to apply to the environment during creation
         */
        tags?: TagMap
        /**
         * The optional VPC security groups and subnets that are attached to the environment
         */
        vpcConfig?: VpcConfig
    }
    export interface CreateEnvironmentResponse {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        id: EnvironmentId
        /**
         * Status of the environment, e.g. PENDING
         */
        status: EnvironmentStatus
    }
    export interface Definition {
        /**
         * ECS compatible image to start
         */
        shellImage?: DefinitionShellImageString
    }
    export type DefinitionShellImageString = string
    export interface DeleteEnvironmentRequest {
        clientToken?: ClientToken
        environmentId: EnvironmentId
    }
    export interface DeleteEnvironmentResponse {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        id: EnvironmentId
        /**
         * Status of the environment, e.g. DELETING
         */
        status: EnvironmentStatus
    }
    export interface DevfileConfiguration {
        /**
         * The location of the devfile on the filesystem related to projects directory or the url to the devfile in Devfile Registry
         */
        location: DevfileConfigurationLocationString
    }
    export type DevfileConfigurationLocationString = string
    export type EnvironmentId = string
    export type EnvironmentStatus =
        | 'PENDING'
        | 'RUNNING'
        | 'STARTING'
        | 'STOPPING'
        | 'STOPPED'
        | 'DELETING'
        | 'DELETED'
        | string
    export type EnvironmentSummaries = EnvironmentSummary[]
    export interface EnvironmentSummary {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Creation timestamp in UTC
         */
        createdAt?: Timestamp
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        id: EnvironmentId
        /**
         * The IDE runtimes configured for the environment
         */
        ideRuntimes?: IdeRuntimes
        /**
         * Timestamp of the last start in UTC.
         */
        lastStartedAt?: Timestamp
        /**
         * Actual status of the environment, such as RUNNING
         */
        status?: EnvironmentStatus
        /**
         * Tags of the environment
         */
        tags?: TagMap
        /**
         * The ARN of the user that created the environment
         */
        userArn?: UserArn
    }
    export interface ExecCommandSessionConfiguration {
        /**
         * The first list item is the command and the others are the arguments. A maximum of 10 arguments can be provided.
         */
        command: Command
    }
    export interface GetEnvironmentMetadataRequest {
        environmentId: EnvironmentId
    }
    export interface GetEnvironmentMetadataResponse {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Creation timestamp in UTC
         */
        createdAt: Timestamp
        /**
         * Definition used for this environment
         */
        definition?: Definition
        /**
         * The optional ARN of the execution role to be used for launching the environment
         */
        executionRoleArn?: IamRoleArn
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        id: EnvironmentId
        /**
         * The IDE runtimes configured for the environment
         */
        ideRuntimes?: IdeRuntimes
        inactivityTimeoutMinutes?: InactivityTimeoutMinutes
        /**
         * The optional Instance Type to use for the MDE environment CPU and RAM
         */
        instanceType: InstanceType
        /**
         * Timestamp of the last start in UTC.
         */
        lastStartedAt?: Timestamp
        /**
         * Upper limit of Environment lifetime as a timestamp in UTC. Environments have a maximum duration of X hours and will be stopped after this time.
         */
        maxRuntimeReachedAt?: Timestamp
        /**
         * Persistent storage configuration
         */
        persistentStorage?: PersistentStorage
        /**
         * The optional ARN of the role to be used within the environment
         */
        roleArn?: IamRoleArn
        /**
         * Actual status of the environment, such as RUNNING
         */
        status: EnvironmentStatus
        /**
         * Reason for the most recent stop of the environment
         */
        stoppedReason?: String
        /**
         * Tags of the environment
         */
        tags?: TagMap
        /**
         * The ARN of the user that created the environment
         */
        userArn?: UserArn
    }
    export interface GetSessionMetadataRequest {
        environmentId: EnvironmentId
        sessionId: SessionId
    }
    export interface GetSessionMetadataResponse {
        id: SessionId
        /**
         * Session creation timestamp in UTC
         */
        startedAt?: Timestamp
        /**
         * Status of the session
         */
        status?: SessionStatus
    }
    export type IamRoleArn = string
    export interface IdeRuntime {
        /**
         * The identifier of the IDE runtime
         */
        id: IdeRuntimeIdString
        /**
         * The version of the IDE runtime
         */
        version: IdeRuntimeVersionString
    }
    export interface IdeRuntimeConfiguration {
        /**
         * The identifier of the IDE runtime
         */
        id: IdeRuntimeConfigurationIdString
    }
    export type IdeRuntimeConfigurationIdString = string
    export type IdeRuntimeIdString = string
    export type IdeRuntimeVersionString = string
    export type IdeRuntimes = IdeRuntime[]
    export type IdeRuntimesConfiguration = IdeRuntimeConfiguration[]
    export type InactivityTimeoutMinutes = number
    export type InstanceType =
        | 'dev.standard1.micro'
        | 'dev.standard1.small'
        | 'dev.standard1.medium'
        | 'dev.standard1.large'
        | 'mde.small'
        | 'mde.medium'
        | 'mde.large'
        | string
    export interface ListEnvironmentsRequest {
        maxResults?: MaxSize1000
        /**
         * Next token for pagination
         */
        nextToken?: NextToken
    }
    export interface ListEnvironmentsResponse {
        /**
         * List of Environments
         */
        environmentSummaries?: EnvironmentSummaries
        /**
         * Next token for pagination
         */
        nextToken?: NextToken
    }
    export interface ListSessionsRequest {
        environmentId: EnvironmentId
        maxResults?: MaxSize200
        nextToken?: NextToken
    }
    export interface ListSessionsResponse {
        nextToken?: NextToken
        sessionSummaries?: SessionSummaries
    }
    export interface ListTagsForResourceRequest {
        /**
         * Resource to list tags for
         */
        resourceArn: String
    }
    export interface ListTagsForResourceResponse {
        tags?: TagMap
    }
    export type MaxSize1000 = number
    export type MaxSize200 = number
    export type NextToken = string
    export interface PersistentStorage {
        /**
         * Size of the persistent storage in Gb (0,16,32,64), zero for no persistence
         */
        sizeInGiB: PersistentStorageSizeInGiBInteger
    }
    export interface PersistentStorageConfiguration {
        /**
         * Size of the persistent storage in GiB (0,16,32,64), zero for no persistence
         */
        sizeInGiB: PersistentStorageConfigurationSizeInGiBInteger
    }
    export type PersistentStorageConfigurationSizeInGiBInteger = number
    export type PersistentStorageSizeInGiBInteger = number
    export type SecretArn = string
    export type SecurityGroupId = string
    export type SecurityGroupIds = SecurityGroupId[]
    export interface SessionConfiguration {
        execCommand?: ExecCommandSessionConfiguration
        ssh?: SshSessionConfiguration
    }
    export type SessionId = string
    export type SessionStatus = 'CONNECTED' | 'DISCONNECTED' | string
    export type SessionSummaries = SessionSummary[]
    export interface SessionSummary {
        id: SessionId
        /**
         * Session creation timestamp in UTC
         */
        startedAt?: Timestamp
        /**
         * Status of the session
         */
        status?: SessionStatus
    }
    export interface SourceCodeConfiguration {
        /**
         * The name of the branch to clone
         */
        branch?: SourceCodeConfigurationBranchString
        /**
         * Secret ARNs to use for authentication when cloning source code
         */
        gitSecretArn?: SecretArn
        /**
         * The URI of the source code to clone
         */
        uri: SourceCodeConfigurationUriString
    }
    export type SourceCodeConfigurationBranchString = string
    export type SourceCodeConfigurationList = SourceCodeConfiguration[]
    export type SourceCodeConfigurationUriString = string
    export interface SshSessionConfiguration {}
    export interface StartEnvironmentRequest {
        clientToken?: ClientToken
        /**
         * New environment definition for the environment
         */
        definition?: Definition
        /**
         * The optional Devfile to use
         */
        devfile?: DevfileConfiguration
        environmentId: EnvironmentId
        /**
         * New runtime to be used in the environment
         */
        ideRuntimes?: IdeRuntimesConfiguration
        inactivityTimeoutMinutes?: InactivityTimeoutMinutes
        /**
         * The optional instance type to use for the MDE environment CPU and RAM
         */
        instanceType?: InstanceType
    }
    export interface StartEnvironmentResponse {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        id: EnvironmentId
        /**
         * Status of the environment, e.g. STARTING
         */
        status: EnvironmentStatus
    }
    export interface StartSessionRequest {
        environmentId: EnvironmentId
        /**
         * Session configuration
         */
        sessionConfiguration: SessionConfiguration
    }
    export interface StartSessionResponse {
        /**
         * Access details for the session, potentially new ones
         */
        accessDetails: AccessDetails
        /**
         * Session Identifier
         */
        id: String
    }
    export interface StopEnvironmentRequest {
        clientToken?: ClientToken
        environmentId: EnvironmentId
    }
    export interface StopEnvironmentResponse {
        /**
         * ARN for the Environment
         */
        arn: Arn
        /**
         * Environment Identifier created for this instance, unique within the AWS Account
         */
        id: EnvironmentId
        /**
         * Status of the environment, e.g. STOPPING
         */
        status: EnvironmentStatus
    }
    export interface StopSessionRequest {
        /**
         * Client token for idempotent calls
         */
        clientToken?: ClientToken
        environmentId: EnvironmentId
        sessionId: SessionId
    }
    export type StreamUrl = string
    export type String = string
    export type SubnetId = string
    export type SubnetIds = SubnetId[]
    export type TagKeys = String[]
    export type TagMap = { [key: string]: TagMapValueString }
    export type TagMapKeyString = string
    export type TagMapValueString = string
    export interface TagResourceRequest {
        /**
         * Resource to tag
         */
        resourceArn: String
        tags: TagMap
    }
    export interface TagResourceResponse {}
    export type Timestamp = Date
    export type TokenValue = string
    export interface UntagResourceRequest {
        /**
         * Resource to untag
         */
        resourceArn: String
        /**
         * Keys to untag
         */
        tagKeys: TagKeys
    }
    export interface UntagResourceResponse {}
    export type UserArn = string
    export interface VpcConfig {
        securityGroupIds?: SecurityGroupIds
        subnetIds?: SubnetIds
    }
    /**
     * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
     */
    export type apiVersion = '2021-04-05' | 'latest' | string
    export interface ClientApiVersions {
        /**
         * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
         */
        apiVersion?: apiVersion
    }
    export type ClientConfiguration = ServiceConfigurationOptions & ClientApiVersions
    /**
     * Contains interfaces for use with the ClientMde client.
     */
    export import Types = ClientMde
}
export = ClientMde
