version: 0.2

env:
    variables:
        NODE_OPTIONS: '--max-old-space-size=8192'
        # Implicitly passed by the release pipeline:
        # TOOLKITS_GITHUB_REPO_OWNER

phases:
    install:
        runtime-versions:
            nodejs: 16

    build:
        commands:
            - git clone https://github.com/${TOOLKITS_GITHUB_REPO_OWNER}/aws-toolkit-vscode.git aws-toolkit-vscode
            # checkout master as we want to commit to it later
            - cd aws-toolkit-vscode && git checkout master

artifacts:
    base-directory: aws-toolkit-vscode
    files:
        - '**/*'
